force-app/main/default/objects/Developer__c/Developer__c.object-meta.xml
<CustomObject>
    <label>Desenvolvedor</label>
    <nameField>
        <label>Develope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Desenvolvedor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Projeto</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Data_Fim__c.field-meta.xml
<CustomField>
    <fullName>Data_Fim__c</fullName>
    <label>Data Fim</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Data_Inicio__c.field-meta.xml
<CustomField>
    <fullName>Data_Inicio__c</fullName>
    <label>Data Inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Desenvolvedor</label>
    <referenceTo>Developer__c</referenceTo>
    <relationshipLabel>Projetos</relationshipLabel>
    <relationshipName>Projetos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Tecnologia__c.field-meta.xml
<CustomField>
    <fullName>Tecnologia__c</fullName>
    <label>Tecnologia</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>.NET</fullName>
            </value>
            <value>
                <fullName>Angular</fullName>
            </value>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>Azure</fullName>
            </value>
            <value>
                <fullName>C#</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>Docker</fullName>
            </value>
            <value>
                <fullName>Flutter</fullName>
            </value>
            <value>
                <fullName>Go</fullName>
            </value>
            <value>
                <fullName>Google Cloud</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>Kotlin</fullName>
            </value>
            <value>
                <fullName>Kubernetes</fullName>
            </value>
            <value>
                <fullName>MongoDB</fullName>
            </value>
            <value>
                <fullName>Node.js</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>Pl/SQL</fullName>
            </value>
            <value>
                <fullName>PostgreSQL</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>Ruby</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>SAP ABAP</fullName>
            </value>
            <value>
                <fullName>SQL Server</fullName>
            </value>
            <value>
                <fullName>Swift</fullName>
            </value>
            <value>
                <fullName>TypeScript</fullName>
            </value>
            <value>
                <fullName>Vue.js</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Valor_Projeto__c.field-meta.xml
<CustomField>
    <fullName>Valor_Projeto__c</fullName>
    <label>Valor do Projeto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Developer__c/Project_Developer__c.object-meta.xml
<CustomObject>
    <label>Alocação de Dev em Projeto</label>
    <nameField>
        <label>Alocação em Projeto Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alocações de Dev em Projeto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Developer__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Desenvolvedor</label>
    <referenceTo>Developer__c</referenceTo>
    <relationshipLabel>Alocações de Dev em Projeto</relationshipLabel>
    <relationshipName>Aloca_es_de_Dev_em_Projeto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Developer__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projeto</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Alocações de Dev em Projeto</relationshipLabel>
    <relationshipName>Alocacoes_de_Dev_em_Projeto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DeveloperProjectsController.cls
public with sharing class DeveloperProjectsController {
    @AuraEnabled(cacheable=true)
    public static List<Project__c> getProjectsByDeveloper(Id developerId) {
        List<Project__c> projetos = [
            SELECT Id, Name, Valor_Projeto__c, Tecnologia__c, Data_Inicio__c, Data_Fim__c
            FROM Project__c
            WHERE Id IN (
                SELECT Project__c FROM Project_Developer__c
                WHERE Developer__c = :developerId
            )
        ];
        return projetos;
    }
}