force-app/main/default/objects/Developer__c/Developer__c.object-meta.xml
<CustomObject>
    <label>Desenvolvedor</label>
    <nameField>
        <label>Develope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Desenvolvedor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Developer__c/fields/Disponivel__c.field-meta.xml
<CustomField>
    <fullName>Disponivel__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Está disponível?</inlineHelpText>
    <label>Disponivel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Developer__c/fields/Senioridade__c.field-meta.xml
<CustomField>
    <fullName>Senioridade__c</fullName>
    <label>Senioridade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Pleno</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
            <value>
                <fullName>Arquiteto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Developer__c/Opportunity_Developer__c.object-meta.xml
<CustomObject>
    <label>Alocação de Dev em Oportunidade</label>
    <nameField>
        <displayFormat>ALLOC-{0000}</displayFormat>
        <label>Alocação de Desenvolvedor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alocações de Dev em Oportunidade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Developer__c/fields/Desenvolvedor__c.field-meta.xml
<CustomField>
    <fullName>Desenvolvedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Desenvolvedor</label>
    <referenceTo>Developer__c</referenceTo>
    <relationshipName>Alocacoes_de_Desenvolvedor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Developer__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Alocacoes_de_Desenvolvedor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityDevelopersController.cls
public with sharing class OpportunityDevelopersController {
    @AuraEnabled(cacheable=true)
    public static List<Developer__c> getDevelopersByOpportunity(Id opportunityId) {
        List<Opportunity_Developer__c> joins = [
            SELECT Desenvolvedor__r.Id, Desenvolvedor__r.Name, Desenvolvedor__r.Tecnologia__c,
                   Desenvolvedor__r.Senioridade__c, Desenvolvedor__r.Disponivel__c
            FROM Opportunity_Developer__c
            WHERE Oportunidade__c = :opportunityId
        ];

        List<Developer__c> devs = new List<Developer__c>();
        for (Opportunity_Developer__c od : joins) {
            if (od.Desenvolvedor__r != null) {
                devs.add(od.Desenvolvedor__r);
            }
        }

        return devs;
    }
}