force-app/main/default/objects/Developer__c/Developer__c.object-meta.xml
<CustomObject>
    <label>Desenvolvedor</label>
    <nameField>
        <label>Develope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Desenvolvedor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Developer__c/fields/Disponivel__c.field-meta.xml
<CustomField>
    <fullName>Disponivel__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Está disponível?</inlineHelpText>
    <label>Disponivel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Developer__c/fields/Senioridade__c.field-meta.xml
<CustomField>
    <fullName>Senioridade__c</fullName>
    <label>Senioridade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Pleno</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
            <value>
                <fullName>Arquiteto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Projeto</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Desenvolvedor</label>
    <referenceTo>Developer__c</referenceTo>
    <relationshipLabel>Projetos</relationshipLabel>
    <relationshipName>Projetos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Tecnologia__c.field-meta.xml
<CustomField>
    <fullName>Tecnologia__c</fullName>
    <label>Tecnologia</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>.NET</fullName>
            </value>
            <value>
                <fullName>Angular</fullName>
            </value>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>Azure</fullName>
            </value>
            <value>
                <fullName>C#</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>Docker</fullName>
            </value>
            <value>
                <fullName>Flutter</fullName>
            </value>
            <value>
                <fullName>Go</fullName>
            </value>
            <value>
                <fullName>Google Cloud</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>Kotlin</fullName>
            </value>
            <value>
                <fullName>Kubernetes</fullName>
            </value>
            <value>
                <fullName>MongoDB</fullName>
            </value>
            <value>
                <fullName>Node.js</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>Pl/SQL</fullName>
            </value>
            <value>
                <fullName>PostgreSQL</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>Ruby</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>SAP ABAP</fullName>
            </value>
            <value>
                <fullName>SQL Server</fullName>
            </value>
            <value>
                <fullName>Swift</fullName>
            </value>
            <value>
                <fullName>TypeScript</fullName>
            </value>
            <value>
                <fullName>Vue.js</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Developer__c/Project_Developer__c.object-meta.xml
<CustomObject>
    <label>Alocação de Dev em Projeto</label>
    <nameField>
        <label>Alocação em Projeto Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alocações de Dev em Projeto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Developer__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Desenvolvedor</label>
    <referenceTo>Developer__c</referenceTo>
    <relationshipLabel>Alocações de Dev em Projeto</relationshipLabel>
    <relationshipName>Aloca_es_de_Dev_em_Projeto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Developer__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projeto</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Alocações de Dev em Projeto</relationshipLabel>
    <relationshipName>Alocacoes_de_Dev_em_Projeto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectDevelopersController2.cls
public with sharing class ProjectDevelopersController2 {
    @AuraEnabled(cacheable=true)
    public static List<Developer__c> getDevelopersByProject(Id projectId) {
        List<Project_Developer__c> joins = [
            SELECT Developer__r.Id, Developer__r.Name, Developer__r.Tecnologia__c, 
                   Developer__r.Senioridade__c, Developer__r.Disponivel__c
            FROM Project_Developer__c
            WHERE Project__c = :projectId
        ];

        List<Developer__c> devs = new List<Developer__c>();
        for (Project_Developer__c pd : joins) {
            if (pd.Developer__r != null) {
                devs.add(pd.Developer__r);
            }
        }

        return devs;
    }
}