force-app/main/default/objects/Developer__c/Developer__c.object-meta.xml
<CustomObject>
    <label>Desenvolvedor</label>
    <nameField>
        <label>Develope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Desenvolvedor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Projeto</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Data_Fim__c.field-meta.xml
<CustomField>
    <fullName>Data_Fim__c</fullName>
    <label>Data Fim</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Data_Inicio__c.field-meta.xml
<CustomField>
    <fullName>Data_Inicio__c</fullName>
    <label>Data Inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Desenvolvedor</label>
    <referenceTo>Developer__c</referenceTo>
    <relationshipLabel>Projetos</relationshipLabel>
    <relationshipName>Projetos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Projetos</relationshipLabel>
    <relationshipName>Projetos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Valor_Projeto__c.field-meta.xml
<CustomField>
    <fullName>Valor_Projeto__c</fullName>
    <label>Valor do Projeto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Developer__c/Project_Developer__c.object-meta.xml
<CustomObject>
    <label>Alocação de Dev em Projeto</label>
    <nameField>
        <label>Alocação em Projeto Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alocações de Dev em Projeto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Developer__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Desenvolvedor</label>
    <referenceTo>Developer__c</referenceTo>
    <relationshipLabel>Alocações de Dev em Projeto</relationshipLabel>
    <relationshipName>Aloca_es_de_Dev_em_Projeto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Developer__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projeto</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Alocações de Dev em Projeto</relationshipLabel>
    <relationshipName>Alocacoes_de_Dev_em_Projeto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjetosPorDevController.cls
public with sharing class ProjetosPorDevController {

    @AuraEnabled(cacheable=true)
    public static List<Developer__c> getDesenvolvedores() {
        return [SELECT Id, Name FROM Developer__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<Project__c> getProjetos(Id devId) {
        return [
            SELECT Id, Name, Data_Inicio__c, Data_Fim__c, Valor_Projeto__c, Oportunidade__r.Name
            FROM Project__c
            WHERE Id IN (
                SELECT Project__c FROM Project_Developer__c WHERE Developer__c = :devId
            )
        ];
    }
}